models/Item.php
<?php
namespace hdmodules\content\models;

use Yii;
use yii\behaviors\SluggableBehavior;
use hdmodules\base\behaviors\SeoBehavior;
use hdmodules\base\models\Photo;
use hdmodules\base\behaviors\CacheFlush;
use hdmodules\base\behaviors\SortableModel;
use yii\helpers\ArrayHelper;
use yii\helpers\StringHelper;

use hdmodules\base\multilanguage\MultiLanguageBehavior;
use hdmodules\base\multilanguage\MultiLanguageTrait;
use hdmodules\base\multilanguage\models\TranslationsWithString;
use hdmodules\base\behaviors\PublishBechavior;
use yii\web\UploadedFile;
use hdmodules\base\helpers\Image;

class Item extends \hdmodules\base\components\ActiveRecord
{
    use MultiLanguageTrait;

    const STATUS_OFF = 0;
    const STATUS_ON = 1;


    public static function tableName()
    {
        return 'content_blocks_item';
    }

    public function rules()
    {
        return [
            [['title'], 'required'],
            [['title', 'short', 'text'], 'trim'],
            ['title', 'string', 'max' => 128],
            ['image', 'image'],
            [['block_id', 'views', 'status'], 'integer'],
            ['time', 'default', 'value' => time()],
            ['slug', 'match', 'pattern' => self::$SLUG_PATTERN, 'message' => Yii::t('content', 'Slug can contain only 0-9, a-z and "-" characters (max: 128).')],
            ['slug', 'default', 'value' => null],
            ['status', 'default', 'value' => self::STATUS_ON],
            [['title', 'short', 'text', 'text_1', 'text_2', 'attribute_1', 'attribute_2', 'attribute_3'], 'safe'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'title' => Yii::t('content', 'Title'),
            'text' => Yii::t('content', 'Text'),
            'short' => Yii::t('content/article', 'Short'),
            'image' => Yii::t('content', 'Image'),
            'time' => Yii::t('content', 'Date'),
            'slug' => Yii::t('content', 'Slug'),
        ];
    }

    public function behaviors()
    {
        return [
            'sortable' => [
                'class' => SortableModel::className(),
                'par_id' => 'block_id'
            ],
            'cacheflush' => [
                'class' => CacheFlush::className(),
                'key' => [static::tableName().'_tree', static::tableName().'_flat']
            ],
            'seoBehavior' => SeoBehavior::className(),
            'sluggable' => [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
                'ensureUnique' => true
            ],
            'mlBehavior' => [
                'class' => MultiLanguageBehavior::className(),
                'mlConfig' => [
                    'db_table' => 'translations_with_string',
                    'attributes' => ['title', 'short', 'text', 'text_1', 'text_2', 'attribute_1', 'attribute_2', 'attribute_3'],
                    'admin_routes' => [
                        'content/item/*'
                    ],
                ],
            ],
            'publishBechavior' => [
                'class' => PublishBechavior::className(),
                'table_name' => self::tableName(),
            ],
        ];
    }

    public function getBlock()
    {
        return $this->hasOne(Block::className(), ['id' => 'block_id']);
    }

    public function getPhotos()
    {
        return $this->hasMany(Photo::className(), ['item_id' => 'id'])->where(['class' => self::className()])->sort();
    }

    public function getTranslations()
    {
        return $this->hasMany(TranslationsWithString::className(), ['model_id' => 'id'])->andWhere(['table_name'=>'content_blocks_item', 'lang'=>Yii::$app->language]);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {

            if (isset($_FILES) && !empty($_FILES)) {
                $this->image = UploadedFile::getInstance($this, 'image');
                if ($this->image && $this->validate(['image'])) {
                    $this->image = Image::upload($this->image, 'item');
                } else {
                    if($this->isNewRecord){
                        $this->image = '';
                    }else{
                        $this->image = $this->oldAttributes['image'];
                    }
                }
            }

            if(!$insert && $this->image != $this->oldAttributes['image'] && $this->oldAttributes['image']){
                @unlink(Yii::getAlias('@webroot').$this->oldAttributes['image']);
            }

            return true;
        } else {
            return false;
        }
    }

    public function afterDelete()
    {
        parent::afterDelete();

        if($this->image){
            @unlink(Yii::getAlias('@webroot').$this->image);
        }

        if($this->photos){
            foreach($this->getPhotos()->all() as $photo){
                $photo->delete();
            }
        }
    }

    public static function listAll($slug = null, $keyField = 'id', $valueField = 'title', $asArray = true  )
    {
        if($block = Block::find()->where(['slug'=>$slug])->one()){
            $query = static::find()->where(['block_id'=>$block->id]);
        }else{
            return [];
        }

        if ($asArray) {
            $query->select([$keyField, $valueField])->asArray();
        }

        return ArrayHelper::map($query->all(), $keyField, $valueField);
    }

    public static function find()
    {
        return new ItemQuery(get_called_class());
    }

}

controllers/ItemController.php
<?php
namespace hdmodules\content\controllers;

use Yii;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;

use hdmodules\base\controllers\SortableController;
use hdmodules\base\controllers\StatusController;
use hdmodules\base\controllers\Controller;
use hdmodules\base\helpers\Image;
use hdmodules\content\models\Block;
use hdmodules\content\models\Item;

class ItemController extends Controller
{
    public $viewPath = '@vendor/hdmodules/constructor-content/views/item';

    public $viewPathIndex = '@vendor/hdmodules/constructor-content/views/item';

    public $viewPathPhotos = '@vendor/hdmodules/constructor-content/views/item';

    public $class_model = 'hdmodules\\content\\models\\Item';

    public function behaviors()
    {
        return array_merge( parent::behaviors(),
            [
                'sortable'=>[
                    'class' => SortableController::className(),
                    'model' => Item::className(),
                ],
                [
                    'class' => StatusController::className(),
                    'model' => Item::className()
                ]
            ]
        );
    }

    public function actionIndex($id)
    {
        if(!($model = Block::findOne($id))){
            return $this->redirect(['/item/index']);
        }

        $provider = new \yii\data\ActiveDataProvider([
            'query' => Item::find()->where(['block_id' => $model->id])->orderBy(['order_num' => SORT_DESC]),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        return $this->render($this->viewPathIndex.'/index', [
            'model' => $model,
            'provider'=>$provider
        ]);
    }


    public function actionCreate($id)
    {
        if(!($block = Block::findOne($id))){
            return $this->redirect(['/content/block/index']);
        }

        $model = new $this->class_model();

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else {
                $model->block_id = $block->primaryKey;

                /*if (isset($_FILES)) {
                    $model->image = UploadedFile::getInstance($model, 'image');
                    if ($model->image && $model->validate(['image'])) {
                        $model->image = Image::upload($model->image, 'item');
                    } else {
                        $model->image = '';
                    }
                }*/

                if ($model->save()) {
                    $this->flash('success', Yii::t('content', 'Item created'));
                    return $this->redirect([($block->controller_name ? $block->controller_name.'/edit' :'/content/item/edit'), 'id' => $model->primaryKey]);
                } else {
                    $this->flash('error', Yii::t('content', 'Create error. {0}', $model->formatErrors()));
                    //return $this->refresh();
                }
            }
        }
        //else {
            return $this->render($this->viewPath.'/create', [
                'model' => $model,
                'block' => $block,
            ]);
        //}
    }

    public function actionEdit($id)
    {
        $class_model = $this->class_model;

        if(!($model = $class_model::findOne($id))){
            return $this->redirect(['/block/index']);
        }

        $model->loadTranslations_custom();

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else {
                /*if (isset($_FILES)) {
                    $model->image = UploadedFile::getInstance($model, 'image');
                    if ($model->image && $model->validate(['image'])) {
                        $model->image = Image::upload($model->image, 'item');
                    } else {
                        $model->image = $model->oldAttributes['image'];
                    }
                }*/

                if ($model->save()) {
                    $this->flash('success', Yii::t('content', 'Item updated'));
                    return $this->redirect([($model->block->controller_name ? $model->block->controller_name.'/edit' :'/content/item/edit'), 'id' => $model->primaryKey]);
                } else {
                    $this->flash('error', Yii::t('content', 'Update error. {0}', $model->formatErrors()));
                    //return $this->refresh();
                }
            }
        }
        //else {
            return $this->render($this->viewPath.'/edit', [
                'model' => $model,
            ]);
        //}
    }

    public function actionPhotos($id)
    {
        $class_model = $this->class_model;

        if(!($model = $class_model::findOne($id))){
            return $this->redirect(['/block/index']);
        }

        return $this->render($this->viewPathPhotos.'/photos', [
            'model' => $model,
        ]);
    }

    public function actionClearImage($id)
    {
        $class_model = $this->class_model;

        $model = $class_model::findOne($id);

        if($model === null){
            $this->flash('error', Yii::t('content', 'Not found'));
        }
        elseif($model->image){
            $model->image = '';
            if($model->save(false)){
                $this->flash('success', Yii::t('content', 'Image cleared'));
            } else {
                $this->flash('error', Yii::t('content', 'Update error. {0}', $model->formatErrors()));
            }
        }
        return $this->back();
    }

    public function actionDelete($id)
    {
        $class_model = $this->class_model;

        if(($model = $class_model::findOne($id))){
            $model->delete();
        } else {
            $this->error = Yii::t('content', 'Not found');
        }
        return $this->formatResponse(Yii::t('content', 'Item deleted'));
    }

    public function actionUp($id, $block_id)
    {
        return $this->move($id, 'up', ['block_id' => $block_id]);
    }

    public function actionDown($id, $block_id)
    {
        return $this->move($id, 'down', ['block_id' => $block_id]);
    }

    public function actionOn($id)
    {
        return $this->changeStatus($id, Item::STATUS_ON);
    }

    public function actionOff($id)
    {
        return $this->changeStatus($id, Item::STATUS_OFF);
    }
}

views/item/_form.php
<?php
use hdmodules\base\helpers\Image;
use hdmodules\base\widgets\SeoForm;
use hdmodules\base\widgets\DateTimePicker;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

use hdmodules\base\multilanguage\input_widget\MultiLanguageActiveField;
use hdmodules\base\widgets\RedactorMultiLanguageInput;

$module = $this->context->module->id;
?>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">

            <div class="x_title">
                <h2><?= Yii::t('content', 'Form') ?> <small><?= Yii::t('content', 'create item') ?></small></h2>
                <ul class="nav navbar-right">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>

            <div class="x_content">

                <?php $form = ActiveForm::begin([
                    'enableAjaxValidation' => true,
                    'validateOnSubmit' => true,
                    'options' => ['enctype' => 'multipart/form-data', 'class' => 'model-form']
                ]); ?>

                    <?= $form->field($model, 'title')->widget(MultiLanguageActiveField::className()) ?>

                    <?php if($model->image) : ?>
                        <img src="<?= Image::thumb($model->image, 240) ?>">
                        <a href="<?= Url::to(['/content/item/clear-image', 'id' => $model->primaryKey]) ?>" class="text-danger confirm-delete" title="<?= Yii::t('content', 'Clear image')?>"><?= Yii::t('content', 'Clear image')?></a>
                    <?php endif; ?>

                    <?= $form->field($model, 'image')->fileInput() ?>

                    <?= $form->field($model, 'short')->textarea()->widget(MultiLanguageActiveField::className(), ['inputType' => 'textArea', 'inputOptions'=>['rows' => '5', 'style'=>['width'=>'100%']]]) ?>

                    <?= RedactorMultiLanguageInput::widget($model, 'text', ['options' => [
                        'minHeight' => 400,
                        'imageUpload' => Url::to(['/redactor/upload', 'dir' => 'items']),
                        'fileUpload' => Url::to(['/redactor/upload', 'dir' => 'items']),
                        'plugins' => ['fullscreen']
                    ]]); ?>
                    <br>
                    <?= RedactorMultiLanguageInput::widget($model, 'text_1', ['options' => [
                        'minHeight' => 400,
                        'imageUpload' => Url::to(['/redactor/upload', 'dir' => 'items']),
                        'fileUpload' => Url::to(['/redactor/upload', 'dir' => 'items']),
                        'plugins' => ['fullscreen']
                    ]]); ?>
                    <br>
                    <?= RedactorMultiLanguageInput::widget($model, 'text_2', ['options' => [
                        'minHeight' => 400,
                        'imageUpload' => Url::to(['/redactor/upload', 'dir' => 'items']),
                        'fileUpload' => Url::to(['/redactor/upload', 'dir' => 'items']),
                        'plugins' => ['fullscreen']
                    ]]); ?>
                    <br>
                    
                    <?= $form->field($model, 'attribute_1') ?>
                    
                    <?= $form->field($model, 'attribute_2') ?>
                    
                    <?= $form->field($model, 'attribute_3') ?>
                    
                    <?= $form->field($model, 'time') ?>

                    <?= $form->field($model, 'slug') ?>

                    <?php if(Yii::$app->controller->action->id == 'create' || (Yii::$app->controller->action->id == 'edit')) : ?>
                        <?= SeoForm::widget(['model' => $model]) ?>
                    <?php endif; ?>

                    <div class="ln_solid"></div>

                    <?= Html::submitButton(Yii::t('content', 'Save'), ['class' => 'btn btn-primary']) ?>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>
</div>

views/item/_menu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;

?>
<ul class="nav nav-pills">
    <?php if($action == 'index') : ?>
        <li><a href="<?= Url::to(['/content/block']) ?>"><i class="glyphicon glyphicon-chevron-left font-12"></i> <?= Yii::t('content', 'Blocks') ?></a></li>
    <?php endif; ?>
    <li <?= ($action == 'index') ? 'class="active"' : '' ?>><a href="<?= Url::to([($block->controller_name ? '/'.$block->controller_name : '/content/item') , 'id' => $block->primaryKey]) ?>"><?php if($action != 'index') echo '<i class="glyphicon glyphicon-chevron-left font-12"></i> ' ?><?= $block->title ?></a></li>
    <li <?= ($action == 'create') ? 'class="active"' : '' ?>><a href="<?= Url::to([($block->controller_name ? $block->controller_name.'/create' : '/content/item/create') , 'id' => $block->primaryKey]) ?>"><?= Yii::t('content', 'Add') ?></a></li>
</ul>
<br/>

views/item/_submenu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;
?>

<ul class="nav nav-tabs">
    <li <?= ($action === 'edit') ? 'class="active"' : '' ?>><a href="<?= Url::to([($model->block->controller_name ? $model->block->controller_name.'/edit' : '/'.$module.'/item/edit'), 'id' => $model->primaryKey]) ?>"><?= Yii::t('easyii/landing', 'Edit item') ?></a></li>
    <li <?= ($action === 'photos') ? 'class="active"' : '' ?>><a href="<?= Url::to([($model->block->controller_name ? $model->block->controller_name.'/photos' : '/'.$module.'/item/photos'), 'id' => $model->primaryKey]) ?>"><span class="glyphicon glyphicon-camera"></span> <?= Yii::t('easyii', 'Photos') ?></a></li>
</ul>
<br>

views/item/create.php
<?php
$this->title = Yii::t('content', 'Create item');
?>
<?= $this->render('_menu', ['block' => $block]) ?>
<?= $this->render('_form', ['model' => $model]) ?>

views/item/edit.php
<?php
$this->title = $model->title;
?>
<?= $this->render('_menu', ['block' => $model->block]) ?>

<?= $this->render('_submenu', ['model' => $model]) ?>

<?= $this->render('_form', ['model' => $model]) ?>

views/item/index.php
<?php
use hdmodules\content\models\Item;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

$this->title = Yii::t('content', 'Items');

$module = $this->context->module->id;
?>
<?= $this->render('_menu', ['block' => $model]) ?>

<div class="col-md-12 col-xs-12">
    <div class="x_panel">

        <div class="x_title"  style="margin-bottom: 30px">
            <h2><?= Yii::t('game', 'Games') ?></h2>
            <ul class="nav navbar-right">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>

        <div class="x_content">

            <?= GridView::widget([
                'dataProvider' =>$provider,
                'summary'=>'',
                'columns' => [
                    [
                        'attribute' => 'id',
                        'contentOptions' => ['width' => '3%'],
                    ],
                    [
                        'attribute' => 'title',
                    ],
                    [
                        'attribute'=>'status',
                        'contentOptions' => ['width' => '90px'],
                        'content'=>function($data){
                            return \kartik\widgets\SwitchInput::widget([
                                'name' => 'status',
                                'options'=>[
                                    'class'=>'switch-input',
                                    'data-id' => $data->primaryKey,
                                    'data-link' => Url::to(['/content/item']),
                                ],
                                'value' => $data->status == \backend\models\GameItemContent::STATUS_ON,
                                'pluginOptions' => [
                                    'size' => 'small',
                                    'onColor' => 'success',
                                    'offColor' => 'danger',
                                ],
                            ]);
                        }
                    ],
                    [
                        'attribute' => 'views',
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'headerOptions' => ['width'=>'85px'],
                        'template'=>'<div class="btn-group btn-group-sm">{up}{down}</div>',
                        'urlCreator' => function ($action, $model, $key, $index) {
                            $url = '';
                            if ($action === 'up')
                                $url = Url::to(['/content/item/up', 'id'=>$model->id, 'block_id' => $model->block->primaryKey]);
                            if ($action === 'down')
                                $url = Url::to(['/content/item/down', 'id'=>$model->id, 'block_id' => $model->block->primaryKey]);

                            return $url;
                        },
                        'buttons' => [
                            'up' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-arrow-up"></span>', $url, [
                                    'title' => Yii::t('hdmodules', 'Move up'),
                                    'class'=>'btn btn-default move-up'
                                ]);
                            },
                            'down' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-arrow-down"></span>', $url, [
                                    'title' => Yii::t('hdmodules', 'Move down'),
                                    'class'=>'btn btn-default move-down'
                                ]);
                            },
                        ],

                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'headerOptions' => ['width'=>'85px'],
                        'template'=>'<div class="btn-group btn-group-sm">{update}{delete}</div>',
                        'urlCreator' => function ($action, $model, $key, $index) {
                            $url = '';
                            if ($action === 'update')
                                $url = Url::to(['/content/item/edit', 'id'=>$model->id]);
                            if ($action === 'delete')
                                $url = Url::to(['/content/item/delete', 'id'=>$model->id]);

                            return $url;
                        },
                        'buttons' => [
                            'update' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                    'title' => Yii::t('hdmodules', 'Update'),
                                    'class'=>'btn btn-default update'
                                ]);
                            },
                            'delete' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                    'title' => Yii::t('hdmodules', 'Delete'),
                                    'class'=>'btn btn-danger delete',
                                    'data-confirm' => Yii::t('app', 'Are you sure you want to delete this Record?'),
                                    'data-method' => 'post'
                                ]);
                            },
                        ],
                    ],
                ],
            ]);
            ?>
        </div>
    </div>
</div>

<?php  $this->registerJs('

$(\'.switch-input\').on(\'switchChange.bootstrapSwitch\', function(event, state){
        var checkbox = $(this);             
        $.getJSON(checkbox.data(\'link\') + \'/\' + (state ? \'on\' : \'off\') + \'/\' + checkbox.data(\'id\'), function(response){                    
            if(response.result === \'error\' || response.result == \'\'){                            
                checkbox.bootstrapSwitch(\'disabled\',true);
                alert(response.error);
            }        
        }).error(function(error) {         
            checkbox.bootstrapSwitch(\'disabled\',true);
            alert(error.statusText);
        });
    });
', \yii\web\View::POS_READY); ?>

views/item/photos.php
<?php
use hdmodules\base\widgets\Photos;

$this->title = $model->title;
?>

<?= $this->render('_menu', ['block' => $model->block]) ?>
<?= $this->render('_submenu', ['model' => $model]) ?>

<?= Photos::widget(['model' => $model])?>