models/Block.php
<?php
namespace hdmodules\content\models;

use Yii;
use yii\behaviors\SluggableBehavior;
use hdmodules\base\behaviors\CacheFlush;
use hdmodules\base\behaviors\SeoBehavior;
use creocoder\nestedsets\NestedSetsBehavior;
use hdmodules\base\components\ActiveQueryNS;

use hdmodules\base\multilanguage\MultiLanguageBehavior;
use hdmodules\base\multilanguage\MultiLanguageTrait;
use yii\helpers\ArrayHelper;

class Block extends \hdmodules\base\components\ActiveRecord
{
    use MultiLanguageTrait;

    const STATUS_OFF = 0;
    const STATUS_ON = 1;

    public static function tableName()
    {
        return 'content_block';
    }

    public function rules()
    {
        return [
            [['slug', 'title'], 'required'],
            ['title', 'trim'],
            ['title', 'string', 'max' => 128],
            ['controller_name', 'string', 'max' => 255],
            ['image', 'image'],
            ['slug', 'match', 'pattern' => self::$SLUG_PATTERN, 'message' => Yii::t('content', 'Slug can contain only 0-9, a-z and "-" characters (max: 128).')],
            ['slug', 'default', 'value' => null],
            ['slug', 'unique'],
            ['status', 'integer'],
            ['status', 'default', 'value' => self::STATUS_ON]
        ];
    }

    public function attributeLabels()
    {
        return [
            'title' => Yii::t('content', 'Title'),
            'image' => Yii::t('content', 'Image'),
            'slug' => Yii::t('content', 'Slug'),
            'controller_name' => Yii::t('content', 'Controller name'),
        ];
    }

    public function behaviors()
    {
        return [
            'cacheflush' => [
                'class' => CacheFlush::className(),
                'key' => [static::tableName().'_tree', static::tableName().'_flat']
            ],
            'seoBehavior' => SeoBehavior::className(),
            /*'sluggable' => [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
                'ensureUnique' => true
            ],*/
            'tree' => [
                'class' => NestedSetsBehavior::className(),
                'treeAttribute' => 'tree'
            ],
            'mlBehavior' => [
                'class' => MultiLanguageBehavior::className(),
                'mlConfig' => [
                    'db_table' => 'translations_with_string',
                    'attributes' => ['title'],
                    'admin_routes' => [
                        'admin/*'
                    ],
                ],
            ],
        ];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if(!$insert && $this->image != $this->oldAttributes['image'] && $this->oldAttributes['image']){
                @unlink(Yii::getAlias('@webroot').$this->oldAttributes['image']);
            }
            return true;
        } else {
            return false;
        }
    }

    /**
     * @return ActiveQueryNS
     */
    public static function find()
    {
        return new ActiveQueryNS(get_called_class());
    }

    /**
     * Get cached tree structure of category objects
     * @return array
     */
    public static function tree()
    {
        $cache = Yii::$app->cache;
        $key = static::tableName().'_tree';

        $tree = $cache->get($key);
        if(!$tree){
            $tree = static::generateTree();
            $cache->set($key, $tree, 3600);
        }
        return $tree;
    }

    /**
     * Get cached flat array of category objects
     * @return array
     */
    public static function cats()
    {
        $cache = Yii::$app->cache;
        $key = static::tableName().'_flat';

        $flat = $cache->get($key);
        if(!$flat){
            $flat = static::generateFlat();
            $cache->set($key, $flat, 3600);
        }
        return $flat;
    }

    /**
     * Generates tree from categories
     * @return array
     */
    public static function generateTree()
    {
        $collection = static::find()->with('seo')->sort()->asArray()->all();
        $trees = array();
        $l = 0;

        if (count($collection) > 0) {
            // Node Stack. Used to help building the hierarchy
            $stack = array();

            foreach ($collection as $node) {
                $item = $node;
                unset($item['lft'], $item['rgt'], $item['order_num']);
                $item['children'] = array();

                // Number of stack items
                $l = count($stack);

                // Check if we're dealing with different levels
                while($l > 0 && $stack[$l - 1]->depth >= $item['depth']) {
                    array_pop($stack);
                    $l--;
                }

                // Stack is empty (we are inspecting the root)
                if ($l == 0) {
                    // Assigning the root node
                    $i = count($trees);
                    $trees[$i] = (object)$item;
                    $stack[] = & $trees[$i];

                } else {
                    // Add node to parent
                    $item['parent'] = $stack[$l - 1]->id;
                    $i = count($stack[$l - 1]->children);
                    $stack[$l - 1]->children[$i] = (object)$item;
                    $stack[] = & $stack[$l - 1]->children[$i];
                }
            }
        }

        return $trees;
    }

    /**
     * Generates flat array of categories
     * @return array
     */
    public static function generateFlat()
    {
        $collection = static::find()->with('seo')->sort()->asArray()->all();
        $flat = [];

        if (count($collection) > 0) {
            $depth = 0;
            $lastId = 0;
            foreach ($collection as $node) {
                $node = (object)$node;
                $id = $node->id;
                $node->parent = '';

                if($node->depth > $depth){
                    $node->parent = $flat[$lastId]->id;
                    $depth = $node->depth;
                } elseif($node->depth == 0){
                    $depth = 0;
                } else {
                    if ($node->depth == $depth) {
                        $node->parent = $flat[$lastId]->parent;
                    } else {
                        foreach($flat as $temp){
                            if($temp->depth == $node->depth){
                                $node->parent = $temp->parent;
                                $depth = $temp->depth;
                                break;
                            }
                        }
                    }
                }
                $lastId = $id;
                unset($node->lft, $node->rgt);
                $flat[$id] = $node;
            }
        }

        foreach($flat as &$node){
            $node->children = [];
            foreach($flat as $temp){
                if($temp->parent == $node->id){
                    $node->children[] = $temp->id;
                }
            }
        }

        return $flat;
    }

    public function getItems()
    {
        return $this->hasMany(Item::className(), ['block_id' => 'id'])->orderBy(['order_num' => SORT_DESC]);
    }
    
    public function getPublishItems()
    {
        return $this->hasMany(Item::className(), ['block_id' => 'id'])
                ->leftJoin('`publish`', '`publish`.model_id = `content_blocks_item`.id')
                ->andWhere(['`publish`.`status`' => 1, '`publish`.`table_name`' => Item::tableName(), '`publish`.`lang`' => Yii::$app->language])
                ->orderBy(['`content_blocks_item`.`order_num`' => SORT_DESC]);
    }
    
    public function afterDelete()
    {
        parent::afterDelete();

        foreach ($this->getItems()->all() as $item) {
            $item->delete();
        }
    }

    public static function listAll($slug, $keyField = 'id', $valueField = 'title', $asArray = true  )
    {
        if($block = Block::find()->where(['slug'=>$slug])->one()){
            $query = $block->children();
        }else{
            return [];
        }

        if ($asArray) {
            $query->select([$keyField, $valueField])->asArray();
        }

        return ArrayHelper::map($query->all(), $keyField, $valueField);
    }
}

controllers/BlockController.php
<?php
namespace hdmodules\content\controllers;

use Yii;
use hdmodules\content\models\Block;
use hdmodules\base\controllers\Controller;
use hdmodules\base\helpers\Image;
use hdmodules\base\behaviors\SortableModel;
use yii\db\ActiveRecord as AR;
use yii\widgets\ActiveForm;
use yii\web\Response;
use yii\web\UploadedFile;


class BlockController extends Controller
{

    public function actionIndex()
    {
        return $this->render('index', [
            'cats' => Block::cats()
        ]);
    }

    public function actionCreate($parent = null)
    {
        $model = new Block();

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else{
                if(isset($_FILES)){
                    $model->image = UploadedFile::getInstance($model, 'image');
                    if($model->image && $model->validate(['image'])){
                        $model->image = Image::upload($model->image, 'block');
                    } else {
                        $model->image = '';
                    }
                }

                $model->status = Block::STATUS_ON;

                $parent = (int)Yii::$app->request->post('parent', null);
                if($parent > 0 && ($parentCategory = Block::findOne($parent))){
                    $model->order_num = $parentCategory->order_num;
                    $model->appendTo($parentCategory);
                } else {
                    $model->attachBehavior('sortable', SortableModel::className());
                    $model->makeRoot();
                }

                if(!$model->hasErrors()){
                    $this->flash('success', Yii::t('content', 'Block created'));
                    return $this->redirect(['/content/block/index']);
                }
                else{
                    $this->flash('error', Yii::t('content', 'Create error. {0}', $model->formatErrors()));
                    return $this->refresh();
                }
            }
        }
        else {
            return $this->render('create', [
                'model' => $model,
                'parent' => $parent
            ]);
        }
    }

    public function actionEdit($id)
    {
        if(!($model = Block::findOne($id))){
            return $this->redirect(['/block/index']);
        }

        $model->loadTranslations_custom();

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else{
                if(isset($_FILES)){
                    $model->image = UploadedFile::getInstance($model, 'image');
                    if($model->image && $model->validate(['image'])){
                        $model->image = Image::upload($model->image, 'block');
                    }else{
                        $model->image = $model->oldAttributes['image'];
                    }
                }
                if($model->save()){
                    $this->flash('success', Yii::t('content', 'Block updated'));
                }
                else{
                    $this->flash('error', Yii::t('content', 'Update error. {0}', $model->formatErrors()));
                }
                return $this->refresh();
            }
        }
        else {
            return $this->render('edit', [
                'model' => $model
            ]);
        }
    }

    public function actionDelete($id)
    {
        if(($model = Block::findOne($id))){
            $children = $model->children()->all();
            $model->deleteWithChildren();
            foreach($children as $child) {
                $child->afterDelete();
            }
        } else {
            $this->error = Yii::t('content', 'Not found');
        }
        return $this->formatResponse(Yii::t('content', 'Block deleted'));
    }

    public function actionClearImage($id)
    {
        $model = Block::findOne($id);

        if($model === null){
            $this->flash('error', Yii::t('content', 'Not found'));
        }
        elseif($model->image){
            $model->image = '';
            if($model->update()){
                $this->flash('success', Yii::t('content', 'Image cleared'));
            } else {
                $this->flash('error', Yii::t('content', 'Update error. {0}', $model->formatErrors()));
            }
        }
        return $this->back();
    }

    public function actionUp($id)
    {
        return $this->move($id, 'up');
    }
    
    public function actionDown($id)
    {
        return $this->move($id, 'down');
    }
    
    public function actionOn($id)
    {
        return $this->changeStatus($id, Block::STATUS_ON);
    }
    
    public function actionOff($id)
    {
        return $this->changeStatus($id, Block::STATUS_OFF);
    }
    
    private function move($id, $direction)
    {
        if(($model = Block::findOne($id)))
        {
            $up = $direction == 'up';
            $orderDir = $up ? SORT_ASC : SORT_DESC;

            if($model->depth == 0){

                $swapCat = Block::find()->where([$up ? '>' : '<', 'order_num', $model->order_num])->orderBy(['order_num' => $orderDir])->one();
                if($swapCat)
                {
                    Block::updateAll(['order_num' => '-1'], ['order_num' => $swapCat->order_num]);
                    Block::updateAll(['order_num' => $swapCat->order_num], ['order_num' => $model->order_num]);
                    Block::updateAll(['order_num' => $model->order_num], ['order_num' => '-1']);
                    $model->trigger(AR::EVENT_AFTER_UPDATE);
                }
            } else {
                $where = [
                    'and',
                    ['tree' => $model->tree],
                    ['depth' => $model->depth],
                    [($up ? '<' : '>'), 'lft', $model->lft]
                ];

                $swapCat = Block::find()->where($where)->orderBy(['lft' => ($up ? SORT_DESC : SORT_ASC)])->one();
                if($swapCat)
                {
                    if($up) {
                        $model->insertBefore($swapCat);
                    } else {
                        $model->insertAfter($swapCat);
                    }

                    $swapCat->update();
                    $model->update();
                }
            }
        }
        else {
            $this->flash('error', Yii::t('content', 'Not found'));
        }
        return $this->back();
    }

    public function changeStatus($id, $status)
    {
        $ids = [];

        if(($model = Block::findOne($id))){
            $ids[] = $model->primaryKey;
            foreach($model->children()->all() as $child){
                $ids[] = $child->primaryKey;
            }
            Block::updateAll(['status' => $status], ['in', 'id', $ids]);
            $model->trigger(AR::EVENT_AFTER_UPDATE);
        }
        else{
            $this->error = Yii::t('content', 'Not found');
        }

        return $this->formatResponse(Yii::t('content', 'Status successfully changed'));
    }
}

views/block/_form.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use hdmodules\base\widgets\SeoForm;
use hdmodules\base\helpers\Image;
use hdmodules\content\models\Block;
use hdmodules\base\multilanguage\input_widget\MultiLanguageActiveField;
?>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            
            <div class="x_title">
                <h2><?= Yii::t('content', 'Form') ?> <small><?= Yii::t('content', 'create block') ?></small></h2>
                <ul class="nav navbar-right">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            
            <div class="x_content">
                
                <?php $form = ActiveForm::begin([
                    'class'=>'form-horizontal form-label-left',
                    'enableAjaxValidation' => true,
                    'options' => ['enctype' => 'multipart/form-data']
                ]); ?>

                <?= $form->field($model, 'title')->widget(MultiLanguageActiveField::className()) ?>

                <?php if(!empty($parent)) : ?>
                    <div class="form-group field-category-title required">
                        <label for="category-parent" class="control-label"><?= Yii::t('content', 'Parent block') ?></label>
                        <select class="form-control" id="category-parent" name="parent">
                            <option value="" class="smooth"><?= Yii::t('easyii', 'No') ?></option>
                            <?php foreach(Block::find()->sort()->asArray()->all() as $node) : ?>
                                <option value="<?= $node['id'] ?>" <?= ($parent == $node['id']) ? 'SELECTED' : '' ?> style="padding-left: <?= $node['depth']*20 ?>px;"><?= $node['title'] ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                <?php endif; ?>

                <?php if($model->image) : ?>
                    <img src="<?= Image::thumb($model->image, 240) ?>">
                    <a href="<?= Url::to(['/content/block/clear-image', 'id' => $model->primaryKey]) ?>" class="text-danger confirm-delete" title="<?= Yii::t('easyii', 'Clear image')?>"><?= Yii::t('easyii', 'Clear image')?></a>
                <?php endif; ?>

                <?= $form->field($model, 'image')->fileInput() ?>

                <?= $form->field($model, 'slug') ?>

                <?= $form->field($model, 'controller_name') ?>

                <?= SeoForm::widget(['model' => $model]) ?>

                <div class="ln_solid"></div>
                <?= Html::submitButton(Yii::t('content', 'Save'), ['class' => 'btn btn-primary']) ?>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>
</div>

views/block/_menu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;
?>
<ul class="nav nav-pills">
    <li <?= ($action === 'index') ? 'class="active"' : '' ?>>
        <a href="<?= Url::to(['/content/block/index']) ?>">
            <?php if($action != 'index') : ?>
                <i class="glyphicon glyphicon-chevron-left font-12"></i>
            <?php endif; ?>
            <?= Yii::t('content', 'Blocks') ?>
        </a>
    </li>
    <li <?= ($action === 'create') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/content/block/create']) ?>"><?= Yii::t('content', 'Create block') ?></a></li>
</ul>
<br/>

views/block/create.php
<?php
$this->title = Yii::t('easyii', 'Create block');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form', ['model' => $model, 'parent' => $parent]) ?>

views/block/edit.php
<?php
$this->title = Yii::t('content', 'Edit block');
?>
<?= $this->render('_menu') ?>

<?php if(!empty($this->params['submenu'])) echo $this->render('_submenu', ['model' => $model], $this->context); ?>

<?= $this->render('_form', ['model' => $model]) ?>

views/block/index.php
<?php
use hdmodules\content\models\Block;
use yii\helpers\Url;

\yii\bootstrap\BootstrapPluginAsset::register($this);

$this->title = 'Bloks';

$baseUrl = '/content';
?>

<?= $this->render('_menu') ?>

<?php if(sizeof($cats) > 0) : ?>
    <table class="table table-hover">
        <tbody>
            <?php foreach($cats as $cat) : ?>
                <tr>
                    <td width="50"><?= $cat->id ?></td>
                    <td style="padding-left:  <?= $cat->depth * 20 ?>px;">
                        <?php if(count($cat->children)) : ?>
                            <i class="caret"></i>
                        <?php endif; ?>
                        <?php if(!count($cat->children)) : ?>
                            <a href="<?= Url::to([ '/'. ($cat->controller_name ? $cat->controller_name : $baseUrl.'/item') , 'id' => $cat->id]) ?>" <?= ($cat->status == Block::STATUS_OFF ? 'class="table-hover"' : '') ?>><?= $cat->title ?></a>
                        <?php else : ?>
                            <span <?= ($cat->status == Block::STATUS_OFF ? 'class="table-hover' : '') ?>><?= $cat->title ?></span>
                        <?php endif; ?>
                    </td>

                    <td width="120" class="text-right" style="overflow: inherit;">
                        <div class="dropdown actions">
                            <i id="dropdownMenu<?= $cat->id ?>" data-toggle="dropdown" aria-expanded="true" title="<?= Yii::t('content', 'Actions') ?>" class="glyphicon glyphicon-menu-hamburger"></i>
                            <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu<?= $cat->id ?>">
                                <li><a href="<?= Url::to([$baseUrl.'/block/edit', 'id' => $cat->id]) ?>"><i class="glyphicon glyphicon-pencil font-12"></i> <?= Yii::t('content', 'Edit') ?></a></li>
                                <li><a href="<?= Url::to([$baseUrl.'/block/create', 'parent' => $cat->id]) ?>"><i class="glyphicon glyphicon-plus font-12"></i> <?= Yii::t('content', 'Add sub block') ?></a></li>
                                <li role="presentation" class="divider"></li>
                                <li><a href="<?= Url::to([$baseUrl.'/block/up', 'id' => $cat->id]) ?>"><i class="glyphicon glyphicon-arrow-up font-12"></i> <?= Yii::t('content', 'Move up') ?></a></li>
                                <li><a href="<?= Url::to([$baseUrl.'/block/down', 'id' => $cat->id]) ?>"><i class="glyphicon glyphicon-arrow-down font-12"></i> <?= Yii::t('content', 'Move down') ?></a></li>
                                <li role="presentation" class="divider"></li>
                                <?php if($cat->status == Block::STATUS_ON) :?>
                                    <li><a href="<?= Url::to([$baseUrl.'/block/off', 'id' => $cat->id]) ?>" title="<?= Yii::t('content', 'Turn Off') ?>'"><i class="glyphicon glyphicon-eye-close font-12"></i> <?= Yii::t('content', 'Turn Off') ?></a></li>
                                <?php else : ?>
                                    <li><a href="<?= Url::to([$baseUrl.'/block/on', 'id' => $cat->id]) ?>" title="<?= Yii::t('content', 'Turn On') ?>"><i class="glyphicon glyphicon-eye-open font-12"></i> <?= Yii::t('content', 'Turn On') ?></a></li>
                                <?php endif; ?>
                                <li><a href="<?= Url::to([$baseUrl.'/block/delete', 'id' => $cat->id]) ?>" class="confirm-delete" data-reload="1" title="<?= Yii::t('content', 'Delete block') ?>"><i class="glyphicon glyphicon-remove font-12"></i> <?= Yii::t('content', 'Delete') ?></a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
<?php else : ?>
    <p><?= Yii::t('content', 'No records found') ?></p>
<?php endif; ?>